name: Zephyr Environment Setup (Composite)
description: |
  This workflow prepares the Zephyr environment for building, testing, or other tasks. It is
  intended to be used as a reusable (composite) step in other workflows.

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Set up Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: .
        toolchains: arm-zephyr-eabi:riscv64-zephyr-elf:x86_64-zephyr-elf:arc-zephyr-elf

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: Set up Zephyr modules
      shell: bash
      run: |
        west config manifest.group-filter -- +optional
        west update

    - name: Cache Zephyr modules
      id: cache-zephyr-modules
      uses: actions/cache@v4
      with:
        path: |
          ../zephyr
          ../modules
          ../bootloader
        key: ${{ hashFiles('west.yml') }}
  
    - name: Install additional dependencies
      shell: bash
      run: |
        pip install protobuf grpcio-tools

    - name: Verify binary blobs
      shell: bash
      run: |
        west blobs fetch

    - name: Apply patches
      shell: bash
      run: |
        west -v patch apply
